spring:
  application:
    name: files-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.1
        max-interval: 2000
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_files
